name: deep-image-prior
channels:
- pytorch
- defaults
dependencies:
- python=3.6.9
- jupyter
- nb_conda
- numpy
- pyyaml
- mkl
- setuptools
- cmake
- cffi
- pytorch=0.4
- matplotlib
- scikit-image
- torchvision
